#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Answers land here, not in .env: this wizard provisions someone else's SaaS
# account and records facts a wayfinder ticket is waiting on. The API key is
# deliberately NOT persisted (ticket #14: where it lives is a build concern).
ENV_FILE="${ENV_FILE:-.scratch/launch-tasks/kit-provisioning-answers.env}"
RAW_DIR=".scratch/launch-tasks/kit-provisioning-raw"
mkdir -p "$(dirname "$ENV_FILE")" "$RAW_DIR"

KIT_API_KEY=""

# kit METHOD PATH [JSON_BODY] -> writes body to $RAW_DIR/last.json, echoes status
kit() {
  local method="$1" path="$2" body="${3:-}" status
  if [[ -n "$body" ]]; then
    status=$(curl -sS -o "$RAW_DIR/last.json" -w '%{http_code}' \
      -X "$method" "https://api.kit.com$path" \
      -H "X-Kit-Api-Key: $KIT_API_KEY" \
      -H 'Content-Type: application/json' \
      --data "$body")
  else
    status=$(curl -sS -o "$RAW_DIR/last.json" -w '%{http_code}' \
      -X "$method" "https://api.kit.com$path" \
      -H "X-Kit-Api-Key: $KIT_API_KEY")
  fi
  printf '%s' "$status"
}

jqr() { jq -r "$1" "$RAW_DIR/last.json" 2>/dev/null || true; }
show_body() { printf '  %s' "$DIM"; jq . "$RAW_DIR/last.json" 2>/dev/null | sed 's/^/  /' || sed 's/^/  /' "$RAW_DIR/last.json"; printf '%s\n' "$RESET"; }
keep() { cp "$RAW_DIR/last.json" "$RAW_DIR/$1.json"; note "raw response kept at $RAW_DIR/$1.json"; }

command -v jq >/dev/null 2>&1 || { printf 'This wizard needs jq. brew install jq\n'; exit 1; }

TOTAL_STAGES=6

banner "Kit provisioning — wayfinder ticket #14"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Kit: API key"
say "Everything after this is an API call made on your behalf. The key is held"
say "in memory for this run only and is never written to disk."
open_url "https://app.kit.com/account_settings/developer_settings"
step "Under 'API Key' (the v4 key, not the older 'API Secret'), click to reveal."
step "If there is no key yet, create one."
ask_secret KIT_API_KEY "Paste the Kit v4 API key:"
[[ -n "$KIT_API_KEY" ]] || { warn "no key entered; nothing further can run"; exit 1; }
say ""
say "Checking the key against GET /v4/account ..."
code=$(kit GET /v4/account)
if [[ "$code" == "200" ]]; then
  printf '  %s✓ key works%s — account: %s\n' "$GREEN" "$RESET" "$(jqr '.account.primary_email_address // .user.email // .account.name // "unknown"')"
  keep account
else
  warn "GET /v4/account returned $code — the key looks wrong. Response:"
  show_body
  confirm "Continue anyway?" || exit 1
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Kit: provision the 'Practice State' custom field"
say "POST /v4/custom_fields  {\"label\": \"Practice State\"}"
note "Idempotent: 201 if created, 200 if it already exists."
note "Label is deliberately 'Practice State', not 'State' — Kit already has a"
note "subscriber 'state' (active/cancelled) meaning something else entirely."
say ""
code=$(kit POST /v4/custom_fields '{"label":"Practice State"}')
show_body
keep custom-field
if [[ "$code" == "200" || "$code" == "201" ]]; then
  FIELD_ID=$(jqr '.custom_field.id')
  FIELD_KEY=$(jqr '.custom_field.key')
  FIELD_NAME=$(jqr '.custom_field.name')
  printf '  %s✓ %s%s (id %s, key %s)\n' "$GREEN" \
    "$([[ "$code" == "201" ]] && echo "created" || echo "already existed")" "$RESET" "$FIELD_ID" "$FIELD_KEY"
  write_env KIT_PRACTICE_STATE_FIELD_ID "$FIELD_ID"
  write_env KIT_PRACTICE_STATE_FIELD_KEY "$FIELD_KEY"
  write_env KIT_PRACTICE_STATE_FIELD_NAME "$FIELD_NAME"
  if [[ "$FIELD_KEY" != "practice_state" ]]; then
    warn "Kit derived '$FIELD_KEY', not the predicted 'practice_state'."
    warn "This is exactly why the key is read from the response. Carry it forward."
  fi
else
  warn "POST /v4/custom_fields returned $code — record this and stop here."
  SKIPPED+=("custom field 'Practice State' (POST returned $code)")
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Kit: provision the 'launch-tasks-signup' tag"
say "From #9: every consented address gets one tag, because broadcast filtering"
say "accepts only segment and tag ids."
say ""
say "GET /v4/tags — looking for an existing 'launch-tasks-signup' ..."
code=$(kit GET "/v4/tags?per_page=500")
TAG_ID=$(jqr '.tags[] | select(.name == "launch-tasks-signup") | .id')
if [[ -n "$TAG_ID" ]]; then
  printf '  %s✓ already exists%s (id %s)\n' "$GREEN" "$RESET" "$TAG_ID"
else
  say "Not found. POST /v4/tags {\"name\": \"launch-tasks-signup\"}"
  code=$(kit POST /v4/tags '{"name":"launch-tasks-signup"}')
  show_body
  keep tag
  TAG_ID=$(jqr '.tag.id')
  if [[ -n "$TAG_ID" ]]; then
    printf '  %s✓ created%s (id %s)\n' "$GREEN" "$RESET" "$TAG_ID"
  else
    warn "POST /v4/tags returned $code with no id."
    SKIPPED+=("tag 'launch-tasks-signup' (POST returned $code)")
  fi
fi
[[ -n "$TAG_ID" ]] && write_env KIT_SIGNUP_TAG_ID "$TAG_ID"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Kit: settle the unknown-field-key contradiction"
say "Kit's spec says both 'the request returns an error' AND 'unknown keys are"
say "ignored, the subscriber is still created, see the warnings array'."
say "Only one can be true, and which one decides whether the sync worker needs"
say "a warnings check at all."
say ""
warn "This creates a REAL subscriber in your Kit account."
say "Use a plus-address you can delete afterwards, e.g. you+kitprobe@yourdomain.com"
ask PROBE_EMAIL "Throwaway email address for the probe:"
if [[ -z "$PROBE_EMAIL" ]]; then
  warn "skipped — the worker's warnings check stays in on the cautious reading"
  SKIPPED+=("unknown-field-key probe (no address given)")
else
  body=$(jq -nc --arg e "$PROBE_EMAIL" \
    '{email_address:$e, fields:{definitely_not_a_real_field_key_xyz:"probe"}}')
  code=$(kit POST /v4/subscribers "$body")
  printf '  %sHTTP %s%s\n' "$BOLD" "$code" "$RESET"
  show_body
  keep unknown-key-probe
  write_env KIT_UNKNOWN_KEY_HTTP_STATUS "$code"
  if [[ "$code" == "200" || "$code" == "201" ]]; then
    W=$(jqr '.warnings // [] | length')
    write_env KIT_UNKNOWN_KEY_BEHAVIOUR "silently-ignored-warnings-${W}"
    warn "Silent partial success: the subscriber was written and the field dropped."
    say "The worker MUST treat a non-empty warnings array on a 2xx as a permanent failure."
  else
    write_env KIT_UNKNOWN_KEY_BEHAVIOUR "hard-error-${code}"
    printf '  %s✓ hard error%s — a bad key fails loudly; the warnings branch is dead code.\n' "$GREEN" "$RESET"
  fi
  say ""
  step "Delete that subscriber in Kit when you're done (Subscribers → search the address)."
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Kit: what plan is this account on?"
say "Segments have historically been gated by plan tier, and the whole"
say "broadcast-targeting path for state runs through a Segment."
say ""
say "GET /v4/account reports a plan_type; the billing page is the authority."
code=$(kit GET /v4/account)
PLAN_TYPE=$(jqr '.account.plan_type // ""')
[[ -n "$PLAN_TYPE" ]] && printf '  %sAPI says plan_type: %s%s\n' "$BOLD" "$PLAN_TYPE" "$RESET"
[[ -n "$PLAN_TYPE" ]] && write_env KIT_PLAN_TYPE_FROM_API "$PLAN_TYPE"
open_url "https://app.kit.com/account_settings/billing"
step "Read the plan name (e.g. Newsletter / Creator / Creator Pro) and the tier."
ask KIT_PLAN_NAME "Plan name as shown on the billing page:"
write_env KIT_PLAN_NAME "$KIT_PLAN_NAME"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Kit: can this plan build a Segment on the custom field?"
say "The load-bearing question. The field now exists, so the Segment builder"
say "should be able to see it."
open_url "https://app.kit.com/subscribers"
step "In the left sidebar, find 'Segments' and click + (or 'Create a segment')."
step "If there is no Segments option, or it is locked behind an upgrade prompt,"
step "  that is the answer — say no below."
step "In the condition builder, open the condition-type dropdown and look for a"
step "  'Custom field' option, then for 'Practice State' in its list."
say ""
if confirm "Can you create a Segment on this plan?"; then
  write_env KIT_SEGMENTS_AVAILABLE "yes"
  if confirm "Does 'Practice State' appear as a Segment condition?"; then
    write_env KIT_SEGMENT_CUSTOM_FIELD_CONDITION "yes"
    printf '  %s✓ #6 holds: field, not 50 tags.%s\n' "$GREEN" "$RESET"
  else
    write_env KIT_SEGMENT_CUSTOM_FIELD_CONDITION "no"
    warn "Segments exist but cannot see the field — #6 needs re-deciding."
  fi
  ask KIT_SEGMENT_CONDITION_WORDING "Exact wording of the condition row (e.g. 'Custom field · Practice State · is'):"
  write_env KIT_SEGMENT_CONDITION_WORDING "$KIT_SEGMENT_CONDITION_WORDING"
  say ""
  note "Don't save a Segment unless you want one — the check is the point, not the artifact."
else
  write_env KIT_SEGMENTS_AVAILABLE "no"
  write_env KIT_SEGMENT_CUSTOM_FIELD_CONDITION "n/a"
  warn "Segments unavailable on this plan. The field is still writable and still"
  warn "queryable via POST /v4/subscribers/filter, but it is NOT broadcast-targetable."
  warn "#6's field-not-tags decision has to be reopened, or the plan upgraded."
fi
pause

finish
say "Answers are in $ENV_FILE; raw responses in $RAW_DIR/."
say "Paste them into wayfinder ticket #14 — and remember the API key was"
say "deliberately not saved anywhere."
printf '\n'
