#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: wayfinder ticket #16 — provision the Kit resubscribe form.
#
#   bash .scratch/launch-tasks/wizards/kit-resubscribe-form.sh
#
# Ticket #15 decided the app can never resubscribe anyone through the API
# (`state` is create-only on POST /v4/subscribers). A Kit-hosted form is the
# only legitimate path back, and the app's only role is to link to it. This
# wizard provisions that form, records its URL, and — the one fact the whole
# design rests on and nobody has observed yet — tests that the form genuinely
# moves a `cancelled` subscriber back to `active`.
# ──────────────────────────────────────────────────────────────────────────

# Answers land here, not in .env: this provisions someone else's SaaS account
# and records facts a wayfinder ticket is waiting on. The API key is
# deliberately NOT persisted (#10, #14, #15: where it lives is a build concern).
ENV_FILE="${ENV_FILE:-.scratch/launch-tasks/kit-resubscribe-form-answers.env}"
RAW_DIR=".scratch/launch-tasks/kit-resubscribe-form-raw"
mkdir -p "$(dirname "$ENV_FILE")" "$RAW_DIR"

KIT_API_KEY=""
SIGNUP_TAG_ID="23720088"          # launch-tasks-signup, provisioned by #14
PROBE_SUB_ID="4301207880"         # cancelled subscriber left behind by #15
PROBE_EMAIL="larsen.ideas+test2@gmail.com"
FORM_NAME="Launch Tasks — Resubscribe"

# kit METHOD PATH [JSON_BODY] -> body to $RAW_DIR/last.json, echoes HTTP status
kit() {
  local method="$1" path="$2" body="${3:-}" status
  if [[ -n "$body" ]]; then
    status=$(curl -sS -o "$RAW_DIR/last.json" -w '%{http_code}' \
      -X "$method" "https://api.kit.com$path" \
      -H "X-Kit-Api-Key: $KIT_API_KEY" \
      -H 'Content-Type: application/json' \
      --data "$body")
  else
    status=$(curl -sS -o "$RAW_DIR/last.json" -w '%{http_code}' \
      -X "$method" "https://api.kit.com$path" \
      -H "X-Kit-Api-Key: $KIT_API_KEY")
  fi
  printf '%s' "$status"
}

jqr() { jq -r "$1" "$RAW_DIR/last.json" 2>/dev/null || true; }
show_body() { printf '  %s' "$DIM"; jq . "$RAW_DIR/last.json" 2>/dev/null | sed 's/^/  /' || sed 's/^/  /' "$RAW_DIR/last.json"; printf '%s\n' "$RESET"; }
keep() { cp "$RAW_DIR/last.json" "$RAW_DIR/$1.json"; note "raw response kept at $RAW_DIR/$1.json"; }

# #15's load-bearing lesson: a raw '+' in a query string reaches Kit as a
# space and the read fails. Encode, always.
urlenc() { python3 -c 'import sys,urllib.parse; print(urllib.parse.quote(sys.argv[1], safe=""))' "$1"; }

command -v jq >/dev/null 2>&1 || { printf 'This wizard needs jq. brew install jq\n'; exit 1; }
command -v python3 >/dev/null 2>&1 || { printf 'This wizard needs python3 (to percent-encode addresses).\n'; exit 1; }

TOTAL_STAGES=8

banner "Kit resubscribe form — wayfinder ticket #16"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "API key, and a subscriber to test against"
say "Everything after this is an API call made on your behalf. The key is held"
say "in memory for this run only and is never written to disk."
open_url "https://app.kit.com/account_settings/developer_settings"
step "Under 'API Key' (the v4 key, not the older 'API Secret'), click to reveal."
ask_secret KIT_API_KEY "Paste the Kit v4 API key:"
[[ -n "$KIT_API_KEY" ]] || { warn "no key entered; nothing further can run"; exit 1; }

say ""
say "Checking the key against GET /v4/account ..."
code=$(kit GET /v4/account)
if [[ "$code" == "200" ]]; then
  printf '  %s✓ key works%s — account: %s\n' "$GREEN" "$RESET" "$(jqr '.account.primary_email_address // .account.name // "unknown"')"
  keep 01-account
else
  warn "GET /v4/account returned $code — the key looks wrong. Response:"
  show_body
  exit 1
fi

say ""
say "Now the test subject. #15 left a cancelled subscriber behind; if it is"
say "still there it is a ready-made way to prove the form actually works."
code=$(kit GET "/v4/subscribers/$PROBE_SUB_ID")
keep 02-probe-subscriber
TEST_SUB_ID=""
TEST_EMAIL=""
if [[ "$code" == "200" && "$(jqr '.subscriber.state')" == "cancelled" ]]; then
  TEST_SUB_ID="$PROBE_SUB_ID"
  TEST_EMAIL="$(jqr '.subscriber.email_address')"
  printf '  %s✓ found%s %s — state %scancelled%s, cancelled at %s\n' \
    "$GREEN" "$RESET" "$TEST_EMAIL" "$BOLD" "$RESET" "$(jqr '.subscriber.canceled_at')"
else
  warn "The probe subscriber is gone or is no longer cancelled (HTTP $code)."
  show_body
  say ""
  say "A fresh one is needed. Give a throwaway plus-address on an inbox you can"
  say "read — the wizard will create it, then unsubscribe it, reproducing the"
  say "exact state a physician who clicked 'unsubscribe' would be in."
  ask TEST_EMAIL "Throwaway address to create and cancel:"
  if [[ -n "$TEST_EMAIL" ]] && confirm "Create '$TEST_EMAIL' in Kit and immediately unsubscribe it?"; then
    code=$(kit POST /v4/subscribers "$(jq -nc --arg e "$TEST_EMAIL" '{email_address:$e,first_name:"ResubProbe"}')")
    keep 03-create-test
    TEST_SUB_ID="$(jqr '.subscriber.id')"
    if [[ -z "$TEST_SUB_ID" || "$TEST_SUB_ID" == "null" ]]; then
      warn "Create returned $code and no subscriber id:"; show_body; exit 1
    fi
    code=$(kit POST "/v4/subscribers/$TEST_SUB_ID/unsubscribe")
    keep 04-cancel-test
    code=$(kit GET "/v4/subscribers/$TEST_SUB_ID")
    keep 05-test-state
    printf '  %s✓ test subject%s %s (id %s) is now state %s\n' \
      "$GREEN" "$RESET" "$TEST_EMAIL" "$TEST_SUB_ID" "$(jqr '.subscriber.state')"
  else
    warn "No test subject. The form can still be provisioned, but stage 8 —"
    warn "the only stage that proves the design works — will have to be skipped."
  fi
fi
[[ -n "$TEST_SUB_ID" ]] && write_env KIT_RESUB_TEST_SUBSCRIBER_ID "$TEST_SUB_ID"
[[ -n "$TEST_EMAIL" ]] && write_env KIT_RESUB_TEST_EMAIL "$TEST_EMAIL"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "What already fires on the launch-tasks-signup tag?"
say "Before deciding whether the new form applies that tag (stage 6), find out"
say "what is already wired to it. Adding a tag that triggers a welcome sequence"
say "would mean a returning physician gets onboarded as if they were new."
open_url "https://app.kit.com/automations/rules"
step "Read the rules list. Note any rule whose trigger or action mentions"
step "  'launch-tasks-signup' (tag id $SIGNUP_TAG_ID)."
open_url "https://app.kit.com/automations"
step "Then check Visual Automations for any entry point of 'Is added to a tag'"
step "  using that tag."
say ""
ask SIGNUP_TAG_AUTOMATIONS "What fires on launch-tasks-signup? ('none' if nothing):"
write_env KIT_SIGNUP_TAG_AUTOMATIONS "$SIGNUP_TAG_AUTOMATIONS"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the form"
say "Named so it is obviously not a signup form — this is the one link the app"
say "hands someone who already told us to stop. It must not look like a trap."
open_url "https://app.kit.com/forms"
step "Audience growth → Landing Pages & Forms → '+ New' → choose 'Form'."
step "Pick any simple inline template; the styling does not matter much —"
step "  this page is reached from a settings screen, not from a website."
step "Name it: $FORM_NAME"
step "Keep the fields to email address only. Do NOT add a 'Practice State'"
step "  field: #13/#14 made practice_state the app's to write, and the app"
step "  will write it on the next Subscribe press anyway."
step "Under Settings → 'Domain name', set a Page URL you can read aloud,"
step "  e.g. 'resubscribe'. Note the full URL it shows."
say ""
pause "Form created and saved?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Confirm double opt-in is ON"
say "This is the one place in this product where a confirmation step is a"
say "feature, not friction. The confirmation email IS the explicit permission"
say "Kit requires before anyone is re-subscribed. Do not turn it off."
open_url "https://app.kit.com/forms"
step "Open '$FORM_NAME' → Settings (in the builder toolbar) →"
step "  'Confirmation email' tab."
step "Find 'Auto-confirm new subscribers'. It must be UNCHECKED."
note "Unchecked = double opt-in ON. Checked would silently resubscribe people."
step "Click 'Edit Email Contents' and read the confirmation email as someone"
step "  who arrived from a settings page, not from a blog post. If it says"
step "  anything like 'thanks for signing up at ...', reword it."
say ""
if confirm "Is 'Auto-confirm new subscribers' unchecked (double opt-in ON)?"; then
  write_env KIT_RESUB_DOUBLE_OPT_IN "on"
  printf '  %s✓ double opt-in confirmed on%s\n' "$GREEN" "$RESET"
else
  warn "Stop and fix this before going further — without it the form is a"
  warn "silent-resubscribe mechanism and the whole consent story collapses."
  write_env KIT_RESUB_DOUBLE_OPT_IN "OFF — NEEDS FIXING"
  confirm "Continue anyway (recording it as broken)?" || exit 1
fi
ask KIT_RESUB_CONFIRM_EMAIL_NOTES "Anything about the confirmation email wording the app must work around?:"
write_env KIT_RESUB_CONFIRM_EMAIL_NOTES "$KIT_RESUB_CONFIRM_EMAIL_NOTES"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The wording the app does not control"
say "Two screens a physician sees in this flow that live in Kit, not in our"
say "app: the form's own copy, and the success message after submitting."
step "In the builder, read the form's headline and body copy. It should say"
step "  what this is — resubscribing to DirectCareTools emails — not 'join"
step "  our newsletter'."
step "Open Settings → the success/confirmation message shown after submit."
step "  It should tell them to go check their inbox and click the link,"
step "  because with double opt-in nothing has happened until they do."
say ""
ask KIT_RESUB_SUCCESS_COPY "Paste the success message the form shows after submit:"
write_env KIT_RESUB_SUCCESS_COPY "$KIT_RESUB_SUCCESS_COPY"
ask KIT_RESUB_COPY_NOTES "Anything the settings-page copy has to compensate for?:"
write_env KIT_RESUB_COPY_NOTES "$KIT_RESUB_COPY_NOTES"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Decide: does the form apply the launch-tasks-signup tag?"
say "You recorded at stage 2: ${SIGNUP_TAG_AUTOMATIONS:-(nothing)}"
say ""
say "The case FOR tagging: a physician who resubscribes through this form and"
say "never returns to the app would otherwise sit in Kit as 'active' but"
say "outside the Launch Tasks audience — subscribed to nothing in particular."
say ""
say "The case AGAINST: #15's Subscribe button re-reads Kit and, seeing them"
say "active again, writes the tag and practice_state itself. So the tag is"
say "not load-bearing — and if anything at stage 2 fires on it, tagging here"
say "onboards a returning physician as though they were brand new."
note "#15: a tag is never proof of consent; only 'state' is. Tagging someone"
note "whose double opt-in Kit has already confirmed does not breach that."
say ""
if confirm "Apply the tag from this form?"; then
  open_url "https://app.kit.com/automations/rules"
  step "'+ New rule' → Trigger: 'Subscribes to a form' → '$FORM_NAME'."
  step "Action: 'Add tag' → 'launch-tasks-signup'. Save."
  note "A rule, not a form field — Kit applies form tags through automations."
  pause "Rule saved?"
  write_env KIT_RESUB_APPLIES_SIGNUP_TAG "yes"
else
  write_env KIT_RESUB_APPLIES_SIGNUP_TAG "no"
  note "Recorded as no. The app tags on the next Subscribe press instead."
fi
ask KIT_RESUB_TAG_RATIONALE "One line on why, for the ticket:"
write_env KIT_RESUB_TAG_RATIONALE "$KIT_RESUB_TAG_RATIONALE"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Capture the form URL — verbatim, from the API"
say "This becomes a constant in the app, so take it from GET /v4/forms rather"
say "than from anything retyped by hand."
code=$(kit GET /v4/forms)
keep 06-forms
if [[ "$code" != "200" ]]; then
  warn "GET /v4/forms returned $code:"; show_body; exit 1
fi
printf '  %sForms on this account:%s\n' "$BOLD" "$RESET"
jq -r '.forms[] | "    \(.id)  \(.name)  →  \(.embed_url)"' "$RAW_DIR/06-forms.json"
say ""
FORM_JSON=$(jq -c --arg n "$FORM_NAME" '.forms[] | select(.name == $n)' "$RAW_DIR/06-forms.json" | head -1)
if [[ -z "$FORM_JSON" ]]; then
  FORM_JSON=$(jq -c '.forms[] | select(.name | test("[Rr]esubscribe"))' "$RAW_DIR/06-forms.json" | head -1)
fi
if [[ -n "$FORM_JSON" ]]; then
  RESUB_FORM_ID=$(jq -r '.id' <<<"$FORM_JSON")
  RESUB_FORM_UID=$(jq -r '.uid' <<<"$FORM_JSON")
  RESUB_FORM_URL=$(jq -r '.embed_url' <<<"$FORM_JSON")
  printf '  %s✓ matched%s id %s, uid %s\n' "$GREEN" "$RESET" "$RESUB_FORM_ID" "$RESUB_FORM_UID"
  printf '  %s%s%s\n' "$BOLD" "$RESUB_FORM_URL" "$RESET"
  confirm "Is that the right form?" || { ask RESUB_FORM_URL "Paste the correct embed_url:"; ask RESUB_FORM_ID "Its id:"; ask RESUB_FORM_UID "Its uid:"; }
else
  warn "No form matched '$FORM_NAME' or /resubscribe/i — pick from the list above."
  ask RESUB_FORM_ID "Form id:"; ask RESUB_FORM_UID "Form uid:"; ask RESUB_FORM_URL "Form embed_url:"
fi
write_env KIT_RESUBSCRIBE_FORM_ID "$RESUB_FORM_ID"
write_env KIT_RESUBSCRIBE_FORM_UID "$RESUB_FORM_UID"
write_env KIT_RESUBSCRIBE_FORM_URL "$RESUB_FORM_URL"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "The only stage that matters: does it actually revive a cancelled one?"
if [[ -z "$TEST_SUB_ID" ]]; then
  warn "No test subject was available at stage 1, so this cannot be run."
  warn "The form exists and its URL is recorded — but the assumption the whole"
  warn "Subscribe-button flow rests on remains UNOBSERVED. Say so in the ticket."
  write_env KIT_RESUB_VERIFIED "no — untested, no cancelled subject available"
else
  say "Everything so far assumed something nobody has watched happen: that a"
  say "Kit form can move a subscriber Kit calls 'cancelled' back to 'active'."
  say "If it cannot, #15's settings copy is promising a way back that does not"
  say "exist, and this ticket has found the thing it was written to find."
  say ""
  printf '  Subject: %s%s%s (id %s)\n' "$BOLD" "$TEST_EMAIL" "$RESET" "$TEST_SUB_ID"
  say ""
  open_url "$RESUB_FORM_URL"
  step "Submit the form with exactly: $TEST_EMAIL"
  step "Open that inbox and click the confirmation link."
  step "Wait for the 'you're confirmed' page before continuing."
  say ""
  pause "Confirmation link clicked?"
  say ""
  say "Reading the subscriber back, two ways ..."
  code=$(kit GET "/v4/subscribers/$TEST_SUB_ID")
  keep 07-after-by-id
  BY_ID_STATE=$(jqr '.subscriber.state')
  ENC=$(urlenc "$TEST_EMAIL")
  code2=$(kit GET "/v4/subscribers?email_address=$ENC&status=all")
  keep 08-after-by-email
  BY_EMAIL_STATE=$(jq -r '.subscribers[0].state // "not found"' "$RAW_DIR/08-after-by-email.json")
  printf '\n  by id    (HTTP %s) → state: %s%s%s\n' "$code" "$BOLD" "$BY_ID_STATE" "$RESET"
  printf '  by email (HTTP %s) → state: %s%s%s\n\n' "$code2" "$BOLD" "$BY_EMAIL_STATE" "$RESET"
  if [[ "$BY_ID_STATE" == "active" ]]; then
    printf '  %s✓ A Kit form DOES revive a cancelled subscriber.%s\n' "$GREEN" "$RESET"
    say "  #15's design holds: link to the form, then let the Subscribe button"
    say "  re-read and clear kit_suppressed_at."
    write_env KIT_RESUB_VERIFIED "yes — cancelled → active after double opt-in confirmation"
  else
    warn "It did NOT return to active. State is '$BY_ID_STATE'."
    warn "This contradicts the assumption #15's Subscribe-button copy rests on."
    warn "Do not close this ticket as done — record the observed state and"
    warn "reopen the question of what the app tells a cancelled physician."
    write_env KIT_RESUB_VERIFIED "NO — stayed '$BY_ID_STATE' after confirmed form submission"
  fi
  write_env KIT_RESUB_OBSERVED_STATE "$BY_ID_STATE"
  say ""
  ask KIT_RESUB_TEST_NOTES "Anything else worth recording about the run?:"
  write_env KIT_RESUB_TEST_NOTES "$KIT_RESUB_TEST_NOTES"
  say ""
  note "The test subscriber is now active in the real audience. Delete it by"
  note "hand in the Kit app when you're done: $TEST_EMAIL"
fi

unset KIT_API_KEY
finish
say "Answers are in $ENV_FILE; raw responses in $RAW_DIR/."
say "Paste both into wayfinder ticket #16 (do not paste the API key)."
